<a href="https://colab.research.google.com/github/Valeriaya512/R/blob/main/R%E5%9F%BA%E6%9C%AC%E8%AA%9E%E6%B3%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Vector

*   裡面要放同類型元素

In [ ]:
a <- c(5 , 46 , -4.5 , 11 , 3.2)
print(a)

[1]  5.0 46.0 -4.5 11.0  3.2

In [ ]:
a <- c('one' , 'two' , 'three')
print(a)

[1] "one"   "two"   "three"

In [ ]:
a <- c(1 , one , 3.1 , "apple")
print(a)

ERROR: Error: object 'one' not found

In [ ]:
a <- 32:56
print(a)

 [1] 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56

**[]：中括號**


1.   指定元素的index
2.   更新特定位置的數字
3.   篩選特定數值

In [ ]:
a <- 5:12
b <- a[c(2,4)] #指定a的第2和第4位置
print(b)

[1] 6 8

In [ ]:
a <- 2:9
a[3] <- 3 * a[3] #將第3個數值*3並取代
print(a)

[1]  2  3 12  5  6  7  8  9

In [ ]:
b <- c("one" , "two" , "three")
b == "one"
b[b == "one"]  #抓出含有one字串

[1]  TRUE FALSE FALSE

[1] "one"

## Matrices 二維

In [ ]:
M1 <- matrix( c('a' , 'a' , 'c' , 'b' , 'c' , 'a') , nrow = 2, ncol = 3) #先填column
print(M1)

M2 <- matrix( c('a' , 'a' , 'c' , 'b' , 'c' , 'a') , nrow = 2, ncol = 3, byrow = TRUE) #先填row
print(M2)

     [,1] [,2] [,3]
[1,] "a"  "c"  "c"
[2,] "a"  "b"  "a"
     [,1] [,2] [,3]
[1,] "a"  "a"  "c"
[2,] "b"  "c"  "a"

## Array 儲存多維度資料

In [ ]:
a <- array( c( 'green' , 'yellow') , dim = c(3 , 3 , 2)) #要2個3x3的矩陣
print(a)

, , 1

     [,1]     [,2]     [,3]
[1,] "green"  "yellow" "green"
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green"

, , 2

     [,1]     [,2]     [,3]
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green"
[3,] "yellow" "green"  "yellow"

## 矩陣運算


*   A * B : 矩陣A與矩陣B的元素間兩兩相乘
*   A %*% B : 矩陣乘法A ‧ B
*   t(A) : A的轉置矩陣
*   solve(A) : 矩陣A的反矩陣
*   solve(A,b) : 求線性系統Ax = b的解
*   y <- eigen(A) : y＄val 為A的特徵值，y＄vec 為A的特徵向量
*   y <- svd(A) : y＄u , y＄d , y＄v 為奇異值分解A = UD(V的轉置)的結果

In [ ]:
A <- matrix( c(1, 2, 3, 4), nrow = 2, ncol = 2)
B <- matrix( c(1, 1, 3, 3), nrow = 2, ncol = 2)
print(A)
print(B)

     [,1] [,2]
[1,]    1    3
[2,]    2    4
     [,1] [,2]
[1,]    1    3
[2,]    1    3

In [ ]:
A <- matrix( c(1, 2, 3, 4), nrow = 2, ncol = 2)
B <- matrix( c(1, 1, 3, 3), nrow = 2, ncol = 2)
print(A * B)

     [,1] [,2]
[1,]    1    9
[2,]    2   12

In [ ]:
A <- matrix( c(1, 2, 3, 4), nrow = 2, ncol = 2)
B <- matrix( c(1, 1, 3, 3), nrow = 2, ncol = 2)
print(A %*% B)

     [,1] [,2]
[1,]    4   12
[2,]    6   18

In [ ]:
A <- matrix( c(1, 2, 3, 4), nrow = 2, ncol = 2)
print(t(A))

     [,1] [,2]
[1,]    1    2
[2,]    3    4

In [ ]:
A <- matrix( c(1, 2, 3, 4), nrow = 2, ncol = 2)
print(solve(A))

     [,1] [,2]
[1,]   -2  1.5
[2,]    1 -0.5

In [ ]:
A <- matrix( c(1, 2, 3, 4), nrow = 2, ncol = 2)
b <- c(2, 1)
print(solve(A,b))

[1] -2.5  1.5

In [ ]:
A <- matrix(c(2, 1, 1, 2), nrow = 2, byrow = TRUE)
eig <- eigen(A)

print(eig$values)
print(eig$vectors)

#check
print(eig$vectors %*% diag(eig$values) %*% solve(eig$vectors))

[1] 3 1
          [,1]       [,2]
[1,] 0.7071068 -0.7071068
[2,] 0.7071068  0.7071068
     [,1] [,2]
[1,]    2    1
[2,]    1    2

In [ ]:
A <- matrix(c(1, 2, 3, 4, 5, 6), nrow = 2, byrow = TRUE)

s <- svd(A)

print(s$u)
print(s$d)
print(s$v)

#check
print(s$u %*% diag(s$d) %*% t(s$v))

           [,1]       [,2]
[1,] -0.3863177 -0.9223658
[2,] -0.9223658  0.3863177
[1] 9.5080320 0.7728696
           [,1]       [,2]
[1,] -0.4286671  0.8059639
[2,] -0.5663069  0.1123824
[3,] -0.7039467 -0.5811991
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6

## List

*   可放不同類型元素

In [ ]:
list1 <- list( c(2, 3, 4), 4.2, cos)
print(list1)

[[1]]
[1] 2 3 4

[[2]]
[1] 4.2

[[3]]
function (x)  .Primitive("cos")

In [ ]:
list2 <- list( vector = c(2, 3, 4), numeric = 4.2, func = cos)
names(list2)

[1] "vector"  "numeric" "func"

In [ ]:
list2 <- list( vector = c(2, 3, 4), numeric = 4.2, func = cos)
print(list2)

$vector
[1] 2 3 4

$numeric
[1] 4.2

$func
function (x)  .Primitive("cos")

## Factors
* 遇到類別變數時使用

  *專門儲存類別資料的變數，同時具有字串與整數的特性*

會儲存：


1.   所有不重複的數值作為labels，會被當成字串
2.   每個元素對應到的標籤

In [ ]:
apple_colors <- c('green', 'green', 'red', 'yellow', 'red', 'green')
factor_apple <- factor(apple_colors)

print(factor_apple)

print(nlevels(factor_apple)) #nlevels -> 查詢有多少個lavels

[1] green  green  red    yellow red    green
Levels: green red yellow
[1] 3

## 資料框架 (Data Frames)

具備以下原則：
*   Rows : 通常代表個體(Individuals) 或 觀察對象(Observations)
*   Columns : 通常是變數(Variables)

In [ ]:
name <- c("Amy", "Bob", "Cindy")
age <- c(20, 22, 19)
gender <- c("Female", "Male", "Female")

df <- data.frame(name, age, gender)
print(df)

   name age gender
1   Amy  20 Female
2   Bob  22   Male
3 Cindy  19 Female

In [ ]:
df <- data.frame(
  name = c("Amy", "Bob", "Cindy"),
  age = c(20, 22, 19),
  gender = c("Female", "Male", "Female"))

print(df)

   name age gender
1   Amy  20 Female
2   Bob  22   Male
3 Cindy  19 Female



*   head : 取得資料框前6筆資料(預設是6)
*   tail : 顯示資料框最後幾列的資料(預設6)
*   colnames : 修改或查詢column名稱
*   rownames : 設定row的名稱
*   summary : 顯示資料基本資訊

In [ ]:
df <- data.frame(
  name = c("Amy", "Bob", "Cindy", "Dan", "Eve", "Jessie", "David"),
  age = c(20, 22, 9, 51, 23, 36, 42),
  gender = c("Female", "Male", "Female", "Male", "Female", "Female", "Male")
)

head(df)

  name   age gender
1 Amy    20  Female
2 Bob    22  Male
3 Cindy   9  Female
4 Dan    51  Male
5 Eve    23  Female
6 Jessie 36  Female

In [ ]:
head(df, n=3)

  name  age gender
1 Amy   20  Female
2 Bob   22  Male
3 Cindy  9  Female

In [ ]:
tail(df)

  name   age gender
2 Bob    22  Male
3 Cindy   9  Female
4 Dan    51  Male
5 Eve    23  Female
6 Jessie 36  Female
7 David  42  Male

  name   age gender
5 Eve    23  Female
6 Jessie 36  Female
7 David  42  Male

In [ ]:
tail(df, n=3)

  name   age gender
5 Eve    23  Female
6 Jessie 36  Female
7 David  42  Male

In [ ]:
df <- data.frame(
  name = c("Amy", "Bob", "Cindy"),
  age = c(20, 22, 19),
  gender = c("Female", "Male", "Female"))

colnames(df) <- c("Var_1", "Var_2", "Var_3")
rownames <- c("1", "2", "3")

print(df)

  Var_1 Var_2  Var_3
1   Amy    20 Female
2   Bob    22   Male
3 Cindy    19 Female

In [ ]:
df <- data.frame(
  name = c("Amy", "Bob", "Cindy"),
  age = c(20, 22, 19),
  gender = c("Female", "Male", "Female"))

summary(df)

        name        age              gender
 Length   :3   Min.   :19.00   Length   :3
 N.unique :3   1st Qu.:19.50   N.unique :2
 N.blank  :0   Median :20.00   N.blank  :0
 Min.nchar:3   Mean   :20.33   Min.nchar:4
 Max.nchar:5   3rd Qu.:21.00   Max.nchar:6
               Max.   :22.00

In [ ]:
x <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
summary(x)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   1.00    3.25    5.50    5.50    7.75   10.00

In [ ]:
gender <- factor(c("M", "F", "F", "M", "F"))
summary(gender)

F M
3 2

## 資料結構常用函數


*   length(object) : 元素個數
*   unique(object) : 該物件的獨立元素
*   str(object) : 輸出該物件的基本架構
*   class(object) : 該物件屬於哪種資料架構
*   names(object) : 物件中元素的名稱
*   c(object,object,...) : 將物件合併成一個向量
*   object : 印出物件
*   rm(object) : 從工作空間中移除物件

In [ ]:
x <- c(1, 1, 2, 2, 3, 3, 4)

length(x)
unique(x)

[1] 7

[1] 1 2 3 4

In [ ]:
df <- data.frame(
  name = c("Amy", "Bob", "Cindy", "Bob", "Amy"),
  age = c(17, 22, 34, 22, 45),
  gender = c("Female", "Male", "Female", "Male", "Female"))

unique(df)

  name  age gender
1 Amy   17  Female
2 Bob   22  Male
3 Cindy 34  Female
5 Amy   45  Female

In [ ]:
df <- data.frame(
  name = c("Amy", "Bob", "Cindy", "Bob", "Amy"),
  age = c(17, 22, 34, 22, 45),
  gender = c("Female", "Male", "Female", "Male", "Female"))

str(df)

'data.frame':	5 obs. of  3 variables:
 $ name  : chr  "Amy" "Bob" "Cindy" "Bob" ...
 $ age   : num  17 22 34 22 45
 $ gender: chr  "Female" "Male" "Female" "Male" ...

In [ ]:
df <- data.frame(
  name = c("Amy", "Bob", "Cindy", "Bob", "Amy"),
  age = c(17, 22, 34, 22, 45),
  gender = c("Female", "Male", "Female", "Male", "Female"))

class(df)

[1] "data.frame"

In [ ]:
df <- data.frame(
  name = c("Amy", "Bob", "Cindy", "Bob", "Amy"),
  age = c(17, 22, 34, 22, 45),
  gender = c("Female", "Male", "Female", "Male", "Female"))

names(df)

[1] "name"   "age"    "gender"