<a href="https://colab.research.google.com/github/Valeriaya512/R/blob/main/Tidy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## tidyverse套件
* 用來做資料整理、清理、轉換、視覺化與匯入


1.   dplyr：做資料篩選、排序、選欄、分組、彙總
2.   tidyr：整理資料格式，例如長表與寬表互轉
3.   ggplot2：做資料視覺化，畫圖表
4.   readr：讀取 CSV、TSV 等表格資料
5.   purrr：用更一致的方法處理迴圈和函數式操作
6.   tibble：提供比基本 data.frame 更現代的資料框格式
7.   forcats：處理 factor 類別變數

In [1]:
install.packages("tidyverse") #安裝套件

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [2]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## tibble ：R語言的資料架構

In [4]:
library(tibble)

iris

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1   5.1          3.5         1.4          0.2         setosa
2   4.9          3.0         1.4          0.2         setosa
3   4.7          3.2         1.3          0.2         setosa
4   4.6          3.1         1.5          0.2         setosa
5   5.0          3.6         1.4          0.2         setosa
6   5.4          3.9         1.7          0.4         setosa
7   4.6          3.4         1.4          0.3         setosa
8   5.0          3.4         1.5          0.2         setosa
9   4.4          2.9         1.4          0.2         setosa
10  4.9          3.1         1.5          0.1         setosa
11  5.4          3.7         1.5          0.2         setosa
12  4.8          3.4         1.6          0.2         setosa
13  4.8          3.0         1.4          0.1         setosa
14  4.3          3.0         1.1          0.1         setosa
15  5.8          4.0         1.2          0.2         setosa
16  5.7          4.4         1.5          0.4         setosa
17  5.4          3.9         1.3          0.4         setosa
18  5.1          3.5         1.4          0.3         setosa
19  5.7          3.8         1.7          0.3         setosa
20  5.1          3.8         1.5          0.3         setosa
21  5.4          3.4         1.7          0.2         setosa
22  5.1          3.7         1.5          0.4         setosa
23  4.6          3.6         1.0          0.2         setosa
24  5.1          3.3         1.7          0.5         setosa
25  4.8          3.4         1.9          0.2         setosa
26  5.0          3.0         1.6          0.2         setosa
27  5.0          3.4         1.6          0.4         setosa
28  5.2          3.5         1.5          0.2         setosa
29  5.2          3.4         1.4          0.2         setosa
30  4.7          3.2         1.6          0.2         setosa
⋮   ⋮            ⋮           ⋮            ⋮           ⋮
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [5]:
iris2 <- as_tibble(iris)  #把dataframe轉換成tibble
iris2  #不會印出所有資料

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1   5.1          3.5         1.4          0.2         setosa
2   4.9          3.0         1.4          0.2         setosa
3   4.7          3.2         1.3          0.2         setosa
4   4.6          3.1         1.5          0.2         setosa
5   5.0          3.6         1.4          0.2         setosa
6   5.4          3.9         1.7          0.4         setosa
7   4.6          3.4         1.4          0.3         setosa
8   5.0          3.4         1.5          0.2         setosa
9   4.4          2.9         1.4          0.2         setosa
10  4.9          3.1         1.5          0.1         setosa
11  5.4          3.7         1.5          0.2         setosa
12  4.8          3.4         1.6          0.2         setosa
13  4.8          3.0         1.4          0.1         setosa
14  4.3          3.0         1.1          0.1         setosa
15  5.8          4.0         1.2          0.2         setosa
16  5.7          4.4         1.5          0.4         setosa
17  5.4          3.9         1.3          0.4         setosa
18  5.1          3.5         1.4          0.3         setosa
19  5.7          3.8         1.7          0.3         setosa
20  5.1          3.8         1.5          0.3         setosa
21  5.4          3.4         1.7          0.2         setosa
22  5.1          3.7         1.5          0.4         setosa
23  4.6          3.6         1.0          0.2         setosa
24  5.1          3.3         1.7          0.5         setosa
25  4.8          3.4         1.9          0.2         setosa
26  5.0          3.0         1.6          0.2         setosa
27  5.0          3.4         1.6          0.4         setosa
28  5.2          3.5         1.5          0.2         setosa
29  5.2          3.4         1.4          0.2         setosa
30  4.7          3.2         1.6          0.2         setosa
⋮   ⋮            ⋮           ⋮            ⋮           ⋮
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [34]:
# tibble傳出表格
tb[[1]]

[1] "Alice" "Bob"

In [8]:
# tibble()：用欄(column)來建立資料表
tb1 <- tibble(
  id    = 1:5,
  name  = c("Alice", "Bob", "Charlie", "David", "Eve"),
  score = c(85, 90, 78, 92, 88)
)
tb1

tb2 <- tibble(x = 1:5, y = 1, z = x ^ 2 + y)
tb2

  id name    score
1 1  Alice   85
2 2  Bob     90
3 3  Charlie 78
4 4  David   92
5 5  Eve     88

  x y z
1 1 1  2
2 2 1  5
3 3 1 10
4 4 1 17
5 5 1 26

In [36]:
# tibble傳出表格
tb1[[2]]  #加[]向量

[1] "Alice"   "Bob"     "Charlie" "David"   "Eve"

In [10]:
# tribble()：用列(row)來輸入少量資料
trb3 <- tribble(
  ~x, ~y, ~z,  #欄位名稱前面要加"~"
  "a", 2, 3.6,
  "b", 1, 8.9
)
trb3

  x y z
1 a 2 3.6
2 b 1 8.9

In [11]:
# 增加列
df <- tibble(x = 1 : 3, y = 3 : 1)
add_row(df, x = 4, y = 0)

  x y
1 1 3
2 2 2
3 3 1
4 4 0

In [12]:
# 在第二列插入新的列
df <- tibble(x = 1 : 3, y = 3 : 1)
add_row(df, x = 4, y = 0, .before = 2) #.before <- 要插入到第幾列

  x y
1 1 3
2 4 0
3 2 2
4 3 1

In [13]:
# 插入多個列
df <- tibble(x = 1 : 3, y = 3 : 1)
add_row(df, x = 4 : 6, y = 0 : -2)

  x y
1 1  3
2 2  2
3 3  1
4 4  0
5 5 -1
6 6 -2

In [19]:
# 插入的列可以有缺失值
df <- tibble(x = 1 : 3, y = 3 : 1)
#add_row(df, x = 4)
add_row(df, y = 0)

  x  y
1  1 3
2  2 2
3  3 1
4 NA 0

In [20]:
# 增加欄
df <- tibble(x = 1 : 3, y = 3 : 1)
add_column(df, z = -1 : 1, w = 0)

  x y z  w
1 1 3 -1 0
2 2 2  0 0
3 3 1  1 0

## 將兩個不同的資料集合合併在一起
可使用：
*  bind_rows
*  bind_cols

In [22]:
library(dplyr)  #若已library(tidyverse)，則可不用這步

bind_rows(iris2[1:5, ], iris2[6:10, ] )

   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1  5.1          3.5         1.4          0.2         setosa
2  4.9          3.0         1.4          0.2         setosa
3  4.7          3.2         1.3          0.2         setosa
4  4.6          3.1         1.5          0.2         setosa
5  5.0          3.6         1.4          0.2         setosa
6  5.4          3.9         1.7          0.4         setosa
7  4.6          3.4         1.4          0.3         setosa
8  5.0          3.4         1.5          0.2         setosa
9  4.4          2.9         1.4          0.2         setosa
10 4.9          3.1         1.5          0.1         setosa

In [24]:
bind_cols(iris2 [, 1 : 2], iris[, 3 : 4])

    Sepal.Length Sepal.Width Petal.Length Petal.Width
1   5.1          3.5         1.4          0.2
2   4.9          3.0         1.4          0.2
3   4.7          3.2         1.3          0.2
4   4.6          3.1         1.5          0.2
5   5.0          3.6         1.4          0.2
6   5.4          3.9         1.7          0.4
7   4.6          3.4         1.4          0.3
8   5.0          3.4         1.5          0.2
9   4.4          2.9         1.4          0.2
10  4.9          3.1         1.5          0.1
11  5.4          3.7         1.5          0.2
12  4.8          3.4         1.6          0.2
13  4.8          3.0         1.4          0.1
14  4.3          3.0         1.1          0.1
15  5.8          4.0         1.2          0.2
16  5.7          4.4         1.5          0.4
17  5.4          3.9         1.3          0.4
18  5.1          3.5         1.4          0.3
19  5.7          3.8         1.7          0.3
20  5.1          3.8         1.5          0.3
21  5.4          3.4         1.7          0.2
22  5.1          3.7         1.5          0.4
23  4.6          3.6         1.0          0.2
24  5.1          3.3         1.7          0.5
25  4.8          3.4         1.9          0.2
26  5.0          3.0         1.6          0.2
27  5.0          3.4         1.6          0.4
28  5.2          3.5         1.5          0.2
29  5.2          3.4         1.4          0.2
30  4.7          3.2         1.6          0.2
⋮   ⋮            ⋮           ⋮            ⋮
121 6.9          3.2         5.7          2.3
122 5.6          2.8         4.9          2.0
123 7.7          2.8         6.7          2.0
124 6.3          2.7         4.9          1.8
125 6.7          3.3         5.7          2.1
126 7.2          3.2         6.0          1.8
127 6.2          2.8         4.8          1.8
128 6.1          3.0         4.9          1.8
129 6.4          2.8         5.6          2.1
130 7.2          3.0         5.8          1.6
131 7.4          2.8         6.1          1.9
132 7.9          3.8         6.4          2.0
133 6.4          2.8         5.6          2.2
134 6.3          2.8         5.1          1.5
135 6.1          2.6         5.6          1.4
136 7.7          3.0         6.1          2.3
137 6.3          3.4         5.6          2.4
138 6.4          3.1         5.5          1.8
139 6.0          3.0         4.8          1.8
140 6.9          3.1         5.4          2.1
141 6.7          3.1         5.6          2.4
142 6.9          3.1         5.1          2.3
143 5.8          2.7         5.1          1.9
144 6.8          3.2         5.9          2.3
145 6.7          3.3         5.7          2.5
146 6.7          3.0         5.2          2.3
147 6.3          2.5         5.0          1.9
148 6.5          3.0         5.2          2.0
149 6.2          3.4         5.4          2.3
150 5.9          3.0         5.1          1.8

## Tibble 與 data.frame 的差異
| 項目             | data.frame                             | tibble                                                     |
| -------------- | -------------------------------------- | ---------------------------------------------------------- |
| 列印顯示           | 會顯示所有行與列， datum 多時控制台會很長、很亂            | 只顯示前 10 行和還能納進控制台的欄位，輸出較整潔易讀 sohu+1                        |
| 欄位名稱部分匹配       | df$col 或 df[, "co"] 可能部分匹配，不嚴格         | 部分匹配會直接報錯：Unknown or uninitialised column listendata       |
| 單欄提取結果         | df[, "col"] 會回傳向量（不是 data.frame）       | tb[, "col"] 仍然回傳 tibble（保持表格結構） listendata                 |
| $ 提取           | df$col 回傳向量                            | tb$col 也回傳向量，但 tb[["col"]] 更嚴格                             |
| 新增欄位長度檢查       | 可以新增長度不同的欄位，R 會自動重複（回收）                | 新增欄位長度必須與現有行數一致，否則直接報錯 listendata                          |
| ** factor 轉換** | 預設可能把字串自動轉成 factor（舊版R）                | 不會自動把字串轉成 factor，字串保持為 character csdn                      |
| 建構語法           | data.frame(col1 = ..., col2 = ...)     | tibble(col1 = ..., col2 = ...) 更簡潔，支援自動回收長度 1 向量 csdn      |
| 與 tidyverse 整合 | 多數 tidyverse 函數也能用，但有時會自動轉回 data.frame | 與 dplyr、tidyr、readr 等緊密整合，輸出通常保持 tibble sohu               |
| 性能             | 處理大資料時較慢，尤其在複雜操作時                      | 底層結構更優化，但實際差異不大；大部分速度差異來自 tidyverse 函數，而非 tibble 本身 sohu+2 |
| 支援複雜結構         | 不建議也不擅長儲存 list-columns                 | 支援 list-columns，可儲存複雜結構（如向量、列表） listendata                 |

In [28]:
# data.frame：50 行會全部顯示（或至少很多）
df <- data.frame(
  x = 1:50,
  y = 1:50 * 2
)
df

# tibble：預設只顯示前 10 行
tb <- tibble(
  x = 1:50,
  y = 1:50 * 2
)
tb

   x  y
1   1   2
2   2   4
3   3   6
4   4   8
5   5  10
6   6  12
7   7  14
8   8  16
9   9  18
10 10  20
11 11  22
12 12  24
13 13  26
14 14  28
15 15  30
16 16  32
17 17  34
18 18  36
19 19  38
20 20  40
21 21  42
22 22  44
23 23  46
24 24  48
25 25  50
26 26  52
27 27  54
28 28  56
29 29  58
30 30  60
31 31  62
32 32  64
33 33  66
34 34  68
35 35  70
36 36  72
37 37  74
38 38  76
39 39  78
40 40  80
41 41  82
42 42  84
43 43  86
44 44  88
45 45  90
46 46  92
47 47  94
48 48  96
49 49  98
50 50 100

   x  y
1   1   2
2   2   4
3   3   6
4   4   8
5   5  10
6   6  12
7   7  14
8   8  16
9   9  18
10 10  20
11 11  22
12 12  24
13 13  26
14 14  28
15 15  30
16 16  32
17 17  34
18 18  36
19 19  38
20 20  40
21 21  42
22 22  44
23 23  46
24 24  48
25 25  50
26 26  52
27 27  54
28 28  56
29 29  58
30 30  60
31 31  62
32 32  64
33 33  66
34 34  68
35 35  70
36 36  72
37 37  74
38 38  76
39 39  78
40 40  80
41 41  82
42 42  84
43 43  86
44 44  88
45 45  90
46 46  92
47 47  94
48 48  96
49 49  98
50 50 100

In [30]:
# 單欄提取結果
df <- data.frame(
  x = 1:5,
  y = 6:10
)

tb <- tibble(
  x = 1:5,
  y = 6:10
)

# data.frame：取單欄會變成向量
df[, "x"]     # 是 vector
class(df[, "x"])

# tibble：取單欄仍然是 tibble
tb[, "x"]     # 是 tibble
class(tb[, "x"])

[1] 1 2 3 4 5

[1] "integer"

  x
1 1
2 2
3 3
4 4
5 5

[1] "tbl_df"     "tbl"        "data.frame"

In [32]:
# 新增欄為長度檢查
# data.frame 會自動回收，但 tibble 嚴格檢查，避免隱含錯誤


# data.frame：可以新增不同長度，R 會自動重複
df <- data.frame(x = 1:5)
df$newcol <- c(5, 6)  # 長度 2 vs 5 行，會重複
df

# tibble：長度不一致會直接報錯
tb <- tibble(x = 1:5)
tb$newcol <- c(5, 6)  # 錯誤：長度必須匹配

ERROR: Error in `$<-.data.frame`(`*tmp*`, newcol, value = c(5, 6)): replacement has 2 rows, data has 5

In [33]:
# factor轉換

# data.frame（舊版 R）：預設可能把字串轉成 factor
df <- data.frame(
  name = c("Alice", "Bob")
)
class(df$name)  # 可能是 factor

# tibble：字串保持為 character
tb <- tibble(
  name = c("Alice", "Bob")
)
class(tb$name)  # character

[1] "character"

[1] "character"

In [37]:
# 將資料從tibble轉換成data.frame
tb <- tibble(
  x = 1:50,
  y = 1:50 * 2
)

class(as.data.frame(tb))

[1] "data.frame"