<a href="https://colab.research.google.com/github/Valeriaya512/R/blob/main/%E5%9F%BA%E6%9C%AC%E8%AA%9E%E6%B3%95_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 自訂函數
*目的：避免複製大量重複的程式碼*

一個函數組成包含：

*   Input變數x
*   Output變數y
*   運算程式碼

f <- function(x){運算程式碼； return (y)}

In [4]:
# 未自訂函數

df <- data.frame(
    a = rnorm(10), #rnorm：產生10個來自常態分配的隨機數，預設平均數是0、標準差是1
    b = rnorm(10),
    c = rnorm(10),
    d = rnorm(10)
)

df$a <- (df$a - min(df$a, na.rm = TRUE)) /  # na.rm = TRUE 表示忽略缺失值
  (max(df$a, na.rm = TRUE) - min(df$a, na.rm = TRUE))
df$b <- (df$b - min(df$b, na.rm = TRUE)) /
  (max(df$b, na.rm = TRUE) - min(df$b, na.rm = TRUE))
df$c <- (df$c - min(df$c, na.rm = TRUE)) /
  (max(df$c, na.rm = TRUE) - min(df$c, na.rm = TRUE))
df$d <- (df$d - min(df$d, na.rm = TRUE)) /
  (max(df$d, na.rm = TRUE) - min(df$d, na.rm = TRUE))

df

   a         b          c         d
1  0.7440719 1.00000000 0.3016229 0.03919786
2  0.4483269 0.03474062 1.0000000 0.12184404
3  0.6245706 0.28436847 0.7811278 0.13531080
4  0.8176531 0.92618516 0.0000000 0.99166003
5  1.0000000 0.63430220 0.2042660 1.00000000
6  0.0000000 0.69553276 0.9009472 0.26302340
7  0.7138275 0.81190672 0.4542932 0.00000000
8  0.8954634 0.00000000 0.9456094 0.63893997
9  0.4070337 0.57604608 0.1737193 0.72935387
10 0.6270318 0.03051408 0.8985817 0.30448693

 [1] 0.7440719 0.4483269 0.6245706 0.8176531 1.0000000 0.0000000 0.7138275
 [8] 0.8954634 0.4070337 0.6270318

####自訂函數注意事項：

1.   **函數要簡短清楚**：
    一個函數最好只負責一件事，太長會很難讀，也不好除錯
2.   **參數名稱要有意義**：
    像 x、y 可以用在簡單範例，但正式寫程式時，盡量用看得懂的名稱
3.   **避免依賴外部變數**：
    函數最好只靠輸入參數運作，不要偷偷用工作區裡的變數
4.   **要處理錯誤輸入**：
    例如空向量、非數值、缺失值，最好先檢查再運算
5.   **回傳結果要固定**：
    同一個函數在不同情況下，回傳型態最好一致，方便後續使用
6.   **不要重複寫程式**：
    把常用的流程包成函數，可以減少重複，也比較容易修改

In [8]:
df <- data.frame(
    a = rnorm(10),
    b = rnorm(10),
    c = rnorm(10),
    d = rnorm(10)
)

RescaleByRange <- function(x){
  rng <- range(x, na.rm = TRUE) #先找出x的最小值和最大值
  return((x - rng[1]) / (rng[2] - rng[1])) #把每個值轉成0到1之間，然後回傳
}

#比較兩者之間結果
(df$a - min(df$a, na.rm = TRUE)) /
  (max(df$a, na.rm = TRUE) - min(df$a, na.rm = TRUE)) #將值轉換成0～1

RescaleByRange(df$a)

 [1] 0.5101870 0.2863192 0.0000000 0.9601638 0.2749806 1.0000000 0.5024379
 [8] 0.2636027 0.7265139 0.8598344

 [1] 0.5101870 0.2863192 0.0000000 0.9601638 0.2749806 1.0000000 0.5024379
 [8] 0.2636027 0.7265139 0.8598344

In [11]:
x <- c(3, 8, 2, 10)
rng <- range(x)

print(rng) #印出最小值和最大值

print(rng[1]) #印出最小值

print(rng[2]) #印出最大值

[1]  2 10
[1] 2
[1] 10

In [16]:
#Homework

SummarizeDate <- function(x){
  summary.df <- data.frame(x_mean = mean(x, na.rm = TRUE),
                x_var = var(x, na.rm = TRUE),
                x_max = max(x, na.rm = TRUE),
                x_min = min(x, na.rm = TRUE),
                x_median = median(x, na.rm = TRUE))
  return(summary.df)
}

SummarizeDate(rnorm(10))

  x_mean     x_var     x_max    x_min     x_median
1 -0.1203258 0.8809826 2.202654 -1.183287 -0.2639913

## Boolean 運算元

In [19]:
3 > 5
4 < 8
6 <= 2
7 >= 6
9 == 6
3 == 3
4 != 6
1 != 1

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

AND

*   &
*   &&

OR

*   |
*   ||

備註：

*   & 和 |：適合處理「一整串」布林值
*   && 和 ||：適合寫在 if 裡，只檢查第一個值

| 運算子 | 意思  | 比較方式     | 常見用途    | 範例                              |
| --- | --- | -------- | ------- | ------------------------------- |
| &   | AND | 逐一比較整個向量 | 向量條件判斷  | c(TRUE, FALSE) & c(TRUE, TRUE)  |
| &&  | AND | 只看第一個元素  | if 條件判斷 | TRUE && FALSE                   |
| \|  | OR  | 逐一比較整個向量 | 向量條件判斷  | c(TRUE, FALSE) \| c(FALSE, TRUE) |
| \|\| | OR  | 只看第一個元素  | if 條件判斷 | FALSE \|\| TRUE                 |

In [28]:
age <- 18
has_id <- TRUE

age >= 20 & has_id

[1] FALSE

In [25]:
is_student <- FALSE
is_member <- TRUE

is_student | is_member

[1] TRUE

In [31]:
age <- 20
has_id <- TRUE

age >= 18 && has_id

[1] TRUE

In [27]:
is_student <- FALSE
is_member <- FALSE

is_student || is_member

[1] FALSE

In [42]:
set.seed(0)
x <- runif(8, -1,1)

x

[1]  0.7933944 -0.4689827 -0.2557522  0.1457067  0.8164156 -0.5966361  0.7967794
[8]  0.8893505

In [46]:
0 >= x & x <= 0.5

[1] FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE FALSE

In [59]:
#0 >= x && x <= 0.5 #因x是向量，&&只能處理長度為1的邏輯值

#解決辦法一
print(
  if (all(x >= 0) && all (x <= 0.5)){
    "全部都在範圍內"
  }
)

#解決辦法二
print(
  if (any (x >= 0) && any (x <= 0.5)){
    "至少有一個值在範圍內"
  }
)

NULL
[1] "至少有一個值在範圍內"

In [66]:
#x是單一數值
x <- -0.3

x >= 0 && x <= 0.5
x >= 0 || x <= 0.5

[1] FALSE

[1] TRUE

In [67]:
set.seed(0)
x <- runif(8, -1,1)

x

-0.5 >= x | x <= 0.5

[1]  0.7933944 -0.4689827 -0.2557522  0.1457067  0.8164156 -0.5966361  0.7967794
[8]  0.8893505

[1] FALSE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE

In [70]:
set.seed(0)
x <- runif(8, -1,1)

x
print(
  if (any (x < -0.5) || any (x > 0.5)){
    "有值超出範圍"
  }
)

[1]  0.7933944 -0.4689827 -0.2557522  0.1457067  0.8164156 -0.5966361  0.7967794
[8]  0.8893505

[1] "有值超出範圍"

### set.seed()：固定隨機數
常見搭配：


*   runif：均勻分配隨機數
*   rnorm：常態分配隨機數

In [39]:
set.seed(0)

u <- runif(5)
n <- rnorm(5)

u
n

[1] 0.8966972 0.2655087 0.3721239 0.5728534 0.9082078

[1] -0.8356286  1.5952808  0.3295078 -0.8204684  0.4874291

In [37]:
set.seed(0)  #0：決定起始點。起始點可以自行決定
x <- runif(8, -1, 1)  #產生8個介於-1到1之間的隨機數
y <- rnorm(5, 50, 10)  #產生5個平均數50、標準差10的隨機變數

x
y

[1]  0.7933944 -0.4689827 -0.2557522  0.1457067  0.8164156 -0.5966361  0.7967794
[8]  0.8893505

[1] 54.14641 34.60050 40.71433 47.05280 49.94233

In [40]:
#整合範例
set.seed(0)

df <- data.frame(
  uniform = runif(5),
  normal = rnorm(5)
)

df

  uniform   normal
1 0.8966972 -0.8356286
2 0.2655087  1.5952808
3 0.3721239  0.3295078
4 0.5728534 -0.8204684
5 0.9082078  0.4874291