<a href="https://colab.research.google.com/github/Valeriaya512/R/blob/main/%E8%B3%87%E6%96%99%E8%BD%89%E6%8F%9B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## dplyr套件

| 函式              | 轉成什麼       | 常見用途            |
| --------------- | ---------- | --------------- |
| as_tibble()     | 一般 tibble  | 把現有資料框、矩陣、列表轉格式 |
| as_tibble_row() | 1 列 tibble | 把一個向量變成「一筆資料」   |
| as_tibble_col() | 1 欄 tibble | 把一個向量變成「一個欄位」   |

In [ ]:
library(tibble)

df <- data.frame(a = 1:3, b = c("x", "y", "z"))
as_tibble(df)  #把data frame、matrix、list等物件轉成tibble，常用在你已經有一個資料物件，想改用tidyverse風格處理

as_tibble_row(c(a = 1, b = 2, c = 3))  #把一個向量變成單列tibble，每個元素會變成一個欄位

as_tibble_col(1:3)  #把向量變成單欄tibble，適合想把一串值包成一個欄位時使用

as_tibble_col(1:3, column_name = "score")

  a b
1 1 x
2 2 y
3 3 z

  a b c
1 1 2 3

  value
1 1
2 2
3 3

  score
1 1
2 2
3 3

## 資料篩選與排序
*  filter()：用來篩選列
*  select()：用來篩選欄
*  arrange()：排序

In [ ]:
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris) #as_tibble()：把資料整理成tidyverse常用的表格格式
print(iris.tb)

# A tibble: 150 × 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>
 1          5.1         3.5          1.4         0.2 setosa
 2          4.9         3            1.4         0.2 setosa
 3          4.7         3.2          1.3         0.2 setosa
 4          4.6         3.1          1.5         0.2 setosa
 5          5           3.6          1.4         0.2 setosa
 6          5.4         3.9          1.7         0.4 setosa
 7          4.6         3.4          1.4         0.3 setosa
 8          5           3.4          1.5         0.2 setosa
 9          4.4         2.9          1.4         0.2 setosa
10          4.9         3.1          1.5         0.1 setosa
# ℹ 140 more rows

In [ ]:
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

#f <- filter(iris.tb, Sepal.Length > 7, Petal.Length > 6)
f <- iris.tb %>% filter(Sepal.Length > 7, Petal.Length > 6)
print(f)

# A tibble: 9 × 5
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
         <dbl>       <dbl>        <dbl>       <dbl> <fct>
1          7.6         3            6.6         2.1 virginica
2          7.3         2.9          6.3         1.8 virginica
3          7.2         3.6          6.1         2.5 virginica
4          7.7         3.8          6.7         2.2 virginica
5          7.7         2.6          6.9         2.3 virginica
6          7.7         2.8          6.7         2   virginica
7          7.4         2.8          6.1         1.9 virginica
8          7.9         3.8          6.4         2   virginica
9          7.7         3            6.1         2.3 virginica

In [ ]:
s <- select(iris.tb, Sepal.Length, Sepal.Width)
print(head(s))

# A tibble: 6 × 2
  Sepal.Length Sepal.Width
         <dbl>       <dbl>
1          5.1         3.5
2          4.9         3
3          4.7         3.2
4          4.6         3.1
5          5           3.6
6          5.4         3.9

In [ ]:
library(dplyr)
library(tibble)

In [ ]:
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris.tb %>%
#  filter(Sepal.Length > 5.5, Sepal.Width > 3.3, Species == 'setosa') %>%
  filter(Sepal.Length > 5.5, Sepal.Width > 3.3) %>%
  select(Species)

iris.tb

  Species
1 setosa
2 setosa
3 setosa
4 versicolor
5 virginica
6 virginica
7 virginica
8 virginica
9 virginica

In [ ]:
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris.tb %>%
  arrange(Sepal.Length, Sepal.Width) #預設升冪

print(head(iris.tb,15))

# A tibble: 15 × 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>
 1          4.3         3            1.1         0.1 setosa
 2          4.4         2.9          1.4         0.2 setosa
 3          4.4         3            1.3         0.2 setosa
 4          4.4         3.2          1.3         0.2 setosa
 5          4.5         2.3          1.3         0.3 setosa
 6          4.6         3.1          1.5         0.2 setosa
 7          4.6         3.2          1.4         0.2 setosa
 8          4.6         3.4          1.4         0.3 setosa
 9          4.6         3.6          1           0.2 setosa
10          4.7         3.2          1.3         0.2 setosa
11          4.7         3.2          1.6         0.2 setosa
12          4.8         3            1.4         0.1 setosa
13          4.8         3            1.4         0.3 setosa
14          4.8         3.1          1.6         0.2 setosa
15          4.8         3.4          1.6         0.2 setosa

In [ ]:
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris.tb %>%
  arrange(desc(Sepal.Length), Sepal.Width)  #降冪

print(head(iris.tb,15))

# A tibble: 15 × 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>
 1          7.9         3.8          6.4         2   virginica
 2          7.7         2.6          6.9         2.3 virginica
 3          7.7         2.8          6.7         2   virginica
 4          7.7         3            6.1         2.3 virginica
 5          7.7         3.8          6.7         2.2 virginica
 6          7.6         3            6.6         2.1 virginica
 7          7.4         2.8          6.1         1.9 virginica
 8          7.3         2.9          6.3         1.8 virginica
 9          7.2         3            5.8         1.6 virginica
10          7.2         3.2          6           1.8 virginica
11          7.2         3.6          6.1         2.5 virginica
12          7.1         3            5.9         2.1 virginica
13          7           3.2          4.7         1.4 versicolor
14          6.9         3.1          4.9         1.5 versicolor
15          6.9         3.1          5.4         2.1 virginica

## mutate()
新增或修改欄位，但保留原本所有欄位

功用：
*  新增欄位
*  修改欄位
*  刪除欄位

常見用法：
* 建立計算欄位：mutate(df, total = a + b)。
* 修改原欄位：mutate(df, a = a * 2)。

* 搭配條件判斷：if_else()、case_when()。

* 搭配位移函式：lag()、lead()。

* 做累積計算：cumsum()、cummean()。

In [ ]:
# 新增欄位
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris_tb %>%
  mutate(
  Sepal_Ratio = Sepal.Length / Sepal.Width ,
  Sepal_Ratio_cm = Sepal_Ratio * 2.54
  )
names(iris.tb)
print(head(iris.tb,10))

[1] "Sepal.Length"   "Sepal.Width"    "Petal.Length"   "Petal.Width"
[5] "Species"        "Sepal_Ratio"    "Sepal_Ratio_cm"

# A tibble: 10 × 7
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species Sepal_Ratio
          <dbl>       <dbl>        <dbl>       <dbl> <fct>         <dbl>
 1          5.1         3.5          1.4         0.2 setosa         1.46
 2          4.9         3            1.4         0.2 setosa         1.63
 3          4.7         3.2          1.3         0.2 setosa         1.47
 4          4.6         3.1          1.5         0.2 setosa         1.48
 5          5           3.6          1.4         0.2 setosa         1.39
 6          5.4         3.9          1.7         0.4 setosa         1.38
 7          4.6         3.4          1.4         0.3 setosa         1.35
 8          5           3.4          1.5         0.2 setosa         1.47
 9          4.4         2.9          1.4         0.2 setosa         1.52
10          4.9         3.1          1.5         0.1 setosa         1.58
# ℹ 1 more variable: Sepal_Ratio_cm <dbl>

In [ ]:
# 用if_else()建立分類欄位
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris.tb %>%
  mutate(size = if_else(Sepal.Length > 5, "big", "small"))

print(head(iris.tb,10))

# A tibble: 10 × 6
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species size
          <dbl>       <dbl>        <dbl>       <dbl> <fct>   <chr>
 1          5.1         3.5          1.4         0.2 setosa  big
 2          4.9         3            1.4         0.2 setosa  small
 3          4.7         3.2          1.3         0.2 setosa  small
 4          4.6         3.1          1.5         0.2 setosa  small
 5          5           3.6          1.4         0.2 setosa  small
 6          5.4         3.9          1.7         0.4 setosa  big
 7          4.6         3.4          1.4         0.3 setosa  small
 8          5           3.4          1.5         0.2 setosa  small
 9          4.4         2.9          1.4         0.2 setosa  small
10          4.9         3.1          1.5         0.1 setosa  small

In [ ]:
# 用case_when()做多條件分類
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris.tb %>%
  mutate(size = case_when(
    Sepal.Length < 5 ~ "small",
    Sepal.Length < 6 ~ "medium",
    TRUE ~ "large"
  ))

print(head(iris.tb,10))

# A tibble: 10 × 6
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species size
          <dbl>       <dbl>        <dbl>       <dbl> <fct>   <chr>
 1          5.1         3.5          1.4         0.2 setosa  medium
 2          4.9         3            1.4         0.2 setosa  small
 3          4.7         3.2          1.3         0.2 setosa  small
 4          4.6         3.1          1.5         0.2 setosa  small
 5          5           3.6          1.4         0.2 setosa  medium
 6          5.4         3.9          1.7         0.4 setosa  medium
 7          4.6         3.4          1.4         0.3 setosa  small
 8          5           3.4          1.5         0.2 setosa  medium
 9          4.4         2.9          1.4         0.2 setosa  small
10          4.9         3.1          1.5         0.1 setosa  small

In [ ]:
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

# 取對數或其他轉換
iris.tb1 <- iris.tb %>%
  mutate(log_len = log(Sepal.Length))

print(head(iris.tb1))


# 做比例或標準化
iris.tb2 <- iris.tb %>%
  mutate(prop = Sepal.Length / sum(Sepal.Length))

print(head(iris.tb2))

# A tibble: 6 × 6
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species log_len
         <dbl>       <dbl>        <dbl>       <dbl> <fct>     <dbl>
1          5.1         3.5          1.4         0.2 setosa     1.63
2          4.9         3            1.4         0.2 setosa     1.59
3          4.7         3.2          1.3         0.2 setosa     1.55
4          4.6         3.1          1.5         0.2 setosa     1.53
5          5           3.6          1.4         0.2 setosa     1.61
6          5.4         3.9          1.7         0.4 setosa     1.69
# A tibble: 6 × 6
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species    prop
         <dbl>       <dbl>        <dbl>       <dbl> <fct>     <dbl>
1          5.1         3.5          1.4         0.2 setosa  0.00582
2          4.9         3            1.4         0.2 setosa  0.00559
3          4.7         3.2          1.3         0.2 setosa  0.00536
4          4.6         3.1          1.5         0.2 setosa  0.00525
5          5           3.6          1.4         0.2 setosa  0.00570
6          5.4         3.9          1.7         0.4 setosa  0.00616

In [ ]:
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)
#iris.tb

# lag()：看前一筆
iris.tb1 <- iris.tb %>%
  arrange(Sepal.Length) %>%
  mutate(prev_len = lag(Sepal.Length, n = 2))  # n=2 往前看2筆
#  mutate(prev_len = lag(Sepal.Length, default = 0))  # default = 0：NA補0

print(head(iris.tb1))

# lead()：看下一筆
iris.tb2 <- iris.tb %>%
  arrange(Sepal.Length) %>%
  mutate(next_len = lead(Sepal.Length, n = 2))  # 往後看2筆

print(tail(iris.tb2))

# A tibble: 6 × 6
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species prev_len
         <dbl>       <dbl>        <dbl>       <dbl> <fct>      <dbl>
1          4.3         3            1.1         0.1 setosa      NA
2          4.4         2.9          1.4         0.2 setosa      NA
3          4.4         3            1.3         0.2 setosa       4.3
4          4.4         3.2          1.3         0.2 setosa       4.4
5          4.5         2.3          1.3         0.3 setosa       4.4
6          4.6         3.1          1.5         0.2 setosa       4.4
# A tibble: 6 × 6
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species   next_len
         <dbl>       <dbl>        <dbl>       <dbl> <fct>        <dbl>
1          7.6         3            6.6         2.1 virginica      7.7
2          7.7         3.8          6.7         2.2 virginica      7.7
3          7.7         2.6          6.9         2.3 virginica      7.7
4          7.7         2.8          6.7         2   virginica      7.9
5          7.7         3            6.1         2.3 virginica     NA
6          7.9         3.8          6.4         2   virginica     NA

In [ ]:
# 修改欄位
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris.tb %>%
  mutate(
  Sepal.Length = Sepal.Length * 10
  )
print(head(iris.tb,10))

# A tibble: 10 × 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>
 1           51         3.5          1.4         0.2 setosa
 2           49         3            1.4         0.2 setosa
 3           47         3.2          1.3         0.2 setosa
 4           46         3.1          1.5         0.2 setosa
 5           50         3.6          1.4         0.2 setosa
 6           54         3.9          1.7         0.4 setosa
 7           46         3.4          1.4         0.3 setosa
 8           50         3.4          1.5         0.2 setosa
 9           44         2.9          1.4         0.2 setosa
10           49         3.1          1.5         0.1 setosa

In [ ]:
# 刪除欄位
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris.tb %>%
  mutate(
  Sepal.Length = NULL
  )

print(head(iris.tb,10))

# A tibble: 10 × 4
   Sepal.Width Petal.Length Petal.Width Species
         <dbl>        <dbl>       <dbl> <fct>
 1         3.5          1.4         0.2 setosa
 2         3            1.4         0.2 setosa
 3         3.2          1.3         0.2 setosa
 4         3.1          1.5         0.2 setosa
 5         3.6          1.4         0.2 setosa
 6         3.9          1.7         0.4 setosa
 7         3.4          1.4         0.3 setosa
 8         3.4          1.5         0.2 setosa
 9         2.9          1.4         0.2 setosa
10         3.1          1.5         0.1 setosa

| 函式          | 主要作用    | 會保留原欄位嗎       | 常見用途      |
| ----------- | ------- | ------------- | --------- |
| select()    | 挑選欄位    | 會，只是把沒選到的欄位移除 | 只看需要的變數   |
| mutate()    | 新增/修改欄位 | 會             | 做計算、分類、轉換 |
| transmute() | 新增/修改欄位 | 不會            | 只輸出計算後結果  |

In [ ]:
# transmute 函數：新增或修改欄位後，只留下新欄位，類似「mutate() + select()」的組合
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb1 <- iris.tb %>%
  transmute(ratio = Sepal.Length / Sepal.Width)

iris.tb1

    ratio
1   1.457143
2   1.633333
3   1.468750
4   1.483871
5   1.388889
6   1.384615
7   1.352941
8   1.470588
9   1.517241
10  1.580645
11  1.459459
12  1.411765
13  1.600000
14  1.433333
15  1.450000
16  1.295455
17  1.384615
18  1.457143
19  1.500000
20  1.342105
21  1.588235
22  1.378378
23  1.277778
24  1.545455
25  1.411765
26  1.666667
27  1.470588
28  1.485714
29  1.529412
30  1.468750
⋮   ⋮
121 2.156250
122 2.000000
123 2.750000
124 2.333333
125 2.030303
126 2.250000
127 2.214286
128 2.033333
129 2.285714
130 2.400000
131 2.642857
132 2.078947
133 2.285714
134 2.250000
135 2.346154
136 2.566667
137 1.852941
138 2.064516
139 2.000000
140 2.225806
141 2.161290
142 2.225806
143 2.148148
144 2.125000
145 2.030303
146 2.233333
147 2.520000
148 2.166667
149 1.823529
150 1.966667

## group_by()
用來分組\
*常和 summarise()、mutate() 搭配使用*

In [ ]:
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris.tb %>%
  group_by(Species) %>%
  do(browser())

iris.tb

In [ ]:
library(dplyr)
library(tibble)

trees.tb <- as_tibble(trees)

trees.tb1 <- trees.tb %>%
  group_by(Girth) %>%
  summarise(
  number = n(),
  avg_Height = mean(Height),
  sd_Height = sd(Height),
  max_Height = max(Height),
  min_Height = min(Height)
  ) %>%
    arrange(desc(avg_Height))

trees.tb1

   Girth number avg_Height sd_Height max_Height min_Height
1  20.6  1      87.0             NA  87         87
2  13.3  1      86.0             NA  86         86
3  10.8  1      83.0             NA  83         83
4  17.5  1      82.0             NA  82         82
5  10.7  1      81.0             NA  81         81
6  17.3  1      81.0             NA  81         81
7  11.1  1      80.0             NA  80         80
8  14.2  1      80.0             NA  80         80
9  17.9  1      80.0             NA  80         80
10 18.0  2      80.0       0.000000  80         80
11 12.9  2      79.5       7.778175  85         74
12 11.3  1      79.0             NA  79         79
13 14.0  1      78.0             NA  78         78
14 16.3  1      77.0             NA  77         77
15 11.4  2      76.0       0.000000  76         76
16 11.2  1      75.0             NA  75         75
17 12.0  1      75.0             NA  75         75
18 14.5  1      74.0             NA  74         74
19 10.5  1      72.0             NA  72         72
20 16.0  1      72.0             NA  72         72
21 13.7  1      71.0             NA  71         71
22 11.0  2      70.5       6.363961  75         66
23  8.3  1      70.0             NA  70         70
24 11.7  1      69.0             NA  69         69
25  8.6  1      65.0             NA  65         65
26 13.8  1      64.0             NA  64         64
27  8.8  1      63.0             NA  63         63

In [ ]:
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb1 <- iris.tb %>%
  group_by(Species) %>%
  filter(rank(desc(Sepal.Length)) < 4) %>%  #各組前3名
  arrange(desc(Species),desc(Sepal.Length))

iris.tb1

   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1  7.9          3.8         6.4          2.0         virginica
2  7.7          3.8         6.7          2.2         virginica
3  7.7          2.6         6.9          2.3         virginica
4  7.7          2.8         6.7          2.0         virginica
5  7.7          3.0         6.1          2.3         virginica
6  7.0          3.2         4.7          1.4         versicolor
7  6.9          3.1         4.9          1.5         versicolor
8  6.8          2.8         4.8          1.4         versicolor
9  5.8          4.0         1.2          0.2         setosa
10 5.7          4.4         1.5          0.4         setosa
11 5.7          3.8         1.7          0.3         setosa

##　character vs factor vs ordered factor
* character：只把資料當文字，R 不會自動把它理解成分類，例如姓名、地址、留言
* factor：存放「分類資訊」，會把不同值整理成**有限個** levels，例如性別、血型、教育程度、地區等，讓 R 知道這些值是不同的類別，方便統計分析、建模和繪圖
* ordered factor：除了分類，還明確表示順序，例如 low < medium < high

| 類型             | 用途          | 有沒有順序 | 典型例子      | 常見用途       |
| -------------- | ----------- | ----- | --------- | ---------- |
| character      | 存文字內容本身     | 沒有    | 姓名、地址、備註  | 文字處理、拼接、搜尋 |
| factor         | 存「類別」資料     | 沒有    | 性別、血型、城市  | 分組、統計次數、建模 |
| ordered factor | 存「有高低順序」的類別 | 有     | 等級、滿意度、成績 | 排序、比較、序位分析 |

In [2]:
# character
name <- c("Amy", "Ben", "Cindy")
name

[1] "Amy"   "Ben"   "Cindy"

In [3]:
# factor
gender <- c("male", "female", "female", "male")
gender_f <- factor(gender)
gender_f

[1] male   female female male
Levels: female male

In [4]:
# ordered factor
level <- c("B", "A", "C", "A")
level_f <- factor(level, levels = c("C", "B", "A"), ordered = TRUE)
level_f

[1] B A C A
Levels: C < B < A