<a href="https://colab.research.google.com/github/Valeriaya512/R/blob/main/%E8%B3%87%E6%96%99%E8%BD%89%E6%8F%9B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## dplyr套件

| 函式              | 轉成什麼       | 常見用途            |
| --------------- | ---------- | --------------- |
| as_tibble()     | 一般 tibble  | 把現有資料框、矩陣、列表轉格式 |
| as_tibble_row() | 1 列 tibble | 把一個向量變成「一筆資料」   |
| as_tibble_col() | 1 欄 tibble | 把一個向量變成「一個欄位」   |

In [14]:
library(tibble)

df <- data.frame(a = 1:3, b = c("x", "y", "z"))
as_tibble(df)  #把data frame、matrix、list等物件轉成tibble，常用在你已經有一個資料物件，想改用tidyverse風格處理

as_tibble_row(c(a = 1, b = 2, c = 3))  #把一個向量變成單列tibble，每個元素會變成一個欄位

as_tibble_col(1:3)  #把向量變成單欄tibble，適合想把一串值包成一個欄位時使用

as_tibble_col(1:3, column_name = "score")

  a b
1 1 x
2 2 y
3 3 z

  a b c
1 1 2 3

  value
1 1
2 2
3 3

  score
1 1
2 2
3 3

## 資料篩選與排序
*  filter()：用來篩選列
*  select()：用來篩選欄
*  arrange()：排序

In [74]:
library(dplyr)
library(tibble)

iris.tb <- as_tibble(iris) #as_tibble()：把資料整理成tidyverse常用的表格格式
print(iris.tb)

# A tibble: 150 × 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>
 1          5.1         3.5          1.4         0.2 setosa
 2          4.9         3            1.4         0.2 setosa
 3          4.7         3.2          1.3         0.2 setosa
 4          4.6         3.1          1.5         0.2 setosa
 5          5           3.6          1.4         0.2 setosa
 6          5.4         3.9          1.7         0.4 setosa
 7          4.6         3.4          1.4         0.3 setosa
 8          5           3.4          1.5         0.2 setosa
 9          4.4         2.9          1.4         0.2 setosa
10          4.9         3.1          1.5         0.1 setosa
# ℹ 140 more rows

In [75]:
library(dplyr)

#f <- filter(iris.tb, Sepal.Length > 7, Petal.Length > 6)
f <- iris.tb %>% filter(Sepal.Length > 7, Petal.Length > 6)
print(f)

# A tibble: 9 × 5
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
         <dbl>       <dbl>        <dbl>       <dbl> <fct>
1          7.6         3            6.6         2.1 virginica
2          7.3         2.9          6.3         1.8 virginica
3          7.2         3.6          6.1         2.5 virginica
4          7.7         3.8          6.7         2.2 virginica
5          7.7         2.6          6.9         2.3 virginica
6          7.7         2.8          6.7         2   virginica
7          7.4         2.8          6.1         1.9 virginica
8          7.9         3.8          6.4         2   virginica
9          7.7         3            6.1         2.3 virginica

In [76]:
s <- select(iris.tb, Sepal.Length, Sepal.Width)
print(head(s))

# A tibble: 6 × 2
  Sepal.Length Sepal.Width
         <dbl>       <dbl>
1          5.1         3.5
2          4.9         3
3          4.7         3.2
4          4.6         3.1
5          5           3.6
6          5.4         3.9

In [79]:
iris.tb <- iris.tb %>%
#  filter(Sepal.Length > 5.5, Sepal.Width > 3.3, Species == 'setosa') %>%
  filter(Sepal.Length > 5.5, Sepal.Width > 3.3) %>%
  select(Species)

iris.tb

  Species
1 setosa
2 setosa
3 setosa
4 versicolor
5 virginica
6 virginica
7 virginica
8 virginica
9 virginica

In [37]:
iris.tb <- iris.tb %>%
  arrange(Sepal.Length, Sepal.Width) #預設升冪

print(head(iris.tb,15))

# A tibble: 15 × 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>
 1          4.3         3            1.1         0.1 setosa
 2          4.4         2.9          1.4         0.2 setosa
 3          4.4         3            1.3         0.2 setosa
 4          4.4         3.2          1.3         0.2 setosa
 5          4.5         2.3          1.3         0.3 setosa
 6          4.6         3.1          1.5         0.2 setosa
 7          4.6         3.2          1.4         0.2 setosa
 8          4.6         3.4          1.4         0.3 setosa
 9          4.6         3.6          1           0.2 setosa
10          4.7         3.2          1.3         0.2 setosa
11          4.7         3.2          1.6         0.2 setosa
12          4.8         3            1.4         0.1 setosa
13          4.8         3            1.4         0.3 setosa
14          4.8         3.1          1.6         0.2 setosa
15          4.8         3.4          1.6         0.2 setosa

In [38]:
iris.tb <- iris.tb %>%
  arrange(desc(Sepal.Length), Sepal.Width)  #降冪

print(head(iris.tb,15))

# A tibble: 15 × 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl> <fct>
 1          7.9         3.8          6.4         2   virginica
 2          7.7         2.6          6.9         2.3 virginica
 3          7.7         2.8          6.7         2   virginica
 4          7.7         3            6.1         2.3 virginica
 5          7.7         3.8          6.7         2.2 virginica
 6          7.6         3            6.6         2.1 virginica
 7          7.4         2.8          6.1         1.9 virginica
 8          7.3         2.9          6.3         1.8 virginica
 9          7.2         3            5.8         1.6 virginica
10          7.2         3.2          6           1.8 virginica
11          7.2         3.6          6.1         2.5 virginica
12          7.1         3            5.9         2.1 virginica
13          7           3.2          4.7         1.4 versicolor
14          6.9         3.1          4.9         1.5 versicolor
15          6.9         3.1          5.4         2.1 virginica

## mutate()
功用：
*  新增欄位
*  修改欄位
*  刪除欄位

常見用法：
* 建立計算欄位：mutate(df, total = a + b)。
* 修改原欄位：mutate(df, a = a * 2)。

* 搭配條件判斷：if_else()、case_when()。

* 搭配位移函式：lag()、lead()。

* 做累積計算：cumsum()、cummean()。

In [72]:
# 新增欄位
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris_tb %>%
  mutate(
  Sepal_Ratio = Sepal.Length / Sepal.Width ,
  Sepal_Ratio_cm = Sepal_Ratio * 2.54
  )
names(iris.tb)
print(head(iris.tb,10))

[1] "Sepal.Length"   "Sepal.Width"    "Petal.Length"   "Petal.Width"
[5] "Species"        "Sepal_Ratio"    "Sepal_Ratio_cm"

# A tibble: 10 × 7
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species Sepal_Ratio
          <dbl>       <dbl>        <dbl>       <dbl> <fct>         <dbl>
 1          5.1         3.5          1.4         0.2 setosa         1.46
 2          4.9         3            1.4         0.2 setosa         1.63
 3          4.7         3.2          1.3         0.2 setosa         1.47
 4          4.6         3.1          1.5         0.2 setosa         1.48
 5          5           3.6          1.4         0.2 setosa         1.39
 6          5.4         3.9          1.7         0.4 setosa         1.38
 7          4.6         3.4          1.4         0.3 setosa         1.35
 8          5           3.4          1.5         0.2 setosa         1.47
 9          4.4         2.9          1.4         0.2 setosa         1.52
10          4.9         3.1          1.5         0.1 setosa         1.58
# ℹ 1 more variable: Sepal_Ratio_cm <dbl>

In [73]:
# 用if_else()建立分類欄位
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris.tb %>%
  mutate(size = if_else(Sepal.Length > 5, "big", "small"))

print(head(iris.tb,10))

# A tibble: 10 × 6
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species size
          <dbl>       <dbl>        <dbl>       <dbl> <fct>   <chr>
 1          5.1         3.5          1.4         0.2 setosa  big
 2          4.9         3            1.4         0.2 setosa  small
 3          4.7         3.2          1.3         0.2 setosa  small
 4          4.6         3.1          1.5         0.2 setosa  small
 5          5           3.6          1.4         0.2 setosa  small
 6          5.4         3.9          1.7         0.4 setosa  big
 7          4.6         3.4          1.4         0.3 setosa  small
 8          5           3.4          1.5         0.2 setosa  small
 9          4.4         2.9          1.4         0.2 setosa  small
10          4.9         3.1          1.5         0.1 setosa  small

In [69]:
# 修改欄位
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris.tb %>%
  mutate(
  Sepal.Length = Sepal.Length * 10
  )
print(head(iris.tb,10))

   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1  51           3.5         1.4          0.2         setosa
2  49           3.0         1.4          0.2         setosa
3  47           3.2         1.3          0.2         setosa
4  46           3.1         1.5          0.2         setosa
5  50           3.6         1.4          0.2         setosa
6  54           3.9         1.7          0.4         setosa
7  46           3.4         1.4          0.3         setosa
8  50           3.4         1.5          0.2         setosa
9  44           2.9         1.4          0.2         setosa
10 49           3.1         1.5          0.1         setosa

In [71]:
# 刪除欄位
library(tibble)

iris.tb <- as_tibble(iris)

iris.tb <- iris.tb %>%
  mutate(
  Sepal.Length = NULL
  )

print(head(iris.tb,10))

# A tibble: 10 × 4
   Sepal.Width Petal.Length Petal.Width Species
         <dbl>        <dbl>       <dbl> <fct>
 1         3.5          1.4         0.2 setosa
 2         3            1.4         0.2 setosa
 3         3.2          1.3         0.2 setosa
 4         3.1          1.5         0.2 setosa
 5         3.6          1.4         0.2 setosa
 6         3.9          1.7         0.4 setosa
 7         3.4          1.4         0.3 setosa
 8         3.4          1.5         0.2 setosa
 9         2.9          1.4         0.2 setosa
10         3.1          1.5         0.1 setosa

In [ ]:
# transmute 函數